### ISSUE TITLE
Custom cipher suite causes silent failure

### ISSUE THREAD

**Issue by vemv** [reifyhealth/lein-git-down#21]
Hey there,

I use something like the following in my ~/.ssh/config, as per recommendation of someone else:

```
Host *
  HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa
  Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128
  MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha
  KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sh
```

With that, if I try to depend on a private github repo,  lein-git-down will fail with:

```
Could not transfer artifact foo:bar:pom:5eb8d61b0fa9859baab999056f99b5dd21bc82c4 from/to private-github (git://github.com): ssh://git@github.com/foo/bar: java.lang.NullPointerException
```

and no stracktrace.

I can work around it by commenting out the mentioned cipher suite, but ideally at least lein-git-down could handle more gracefully the situation.

Thanks - Victor

**Comment by manderson202** [comment]
I'm sure this is an artifact of the dated SSH library used by jGit (and by extension, gitlibs). I patched a few holes I found, but this may be another. I'll dig in and see if I can track it down. Thanks for the report!
