### ISSUE TITLE
"Could not find remote git repository" warnings for snapshots

### ISSUE THREAD

**Issue by vemv** [reifyhealth/lein-git-down#31]
Hey there again,

in a private project I consistently get these warnings:

```
Could not find remote git repository at https://github.com/xxx/yyy. Did you add the git coordinates to the `:git-down` key in project.clj? If so, you may not have permissions to read the repository if it is private.

Could not find remote git repository at ssh://git@github.com/com.clojure-goes-fast/clj-java-decompiler. Did you add the git coordinates to the `:git-down` key in project.clj? If so, you may not have permissions to read the repository if it is private.

Could not find remote git repository at ssh://git@github.com/nrepl-debugger/nrepl-debugger. Did you add the git coordinates to the `:git-down` key in project.clj? If so, you may not have permissions to read the repository if it is private.
```

(`xxx/yyy` is a redacted repo)

All of those dependencies have in common that they are snapshots, e.g. `[com.clojure-goes-fast/clj-java-decompiler "0.2.1-SNAPSHOT"]`.

I don't get these warnings for all the dozens of other non-git, non-snapshot dependencies of the project, which are expressed both in project.clj and ~/.lein/profiles.clj.

So perhaps, snapshots need some special treatment to avoid the potentially confusing warnings?

Thanks - Victor

**Comment by manderson202** [comment]
Thanks for the additional detail! I'm still having trouble reproducing the problem, however. Here is the `project.clj` I'm using (trying to reproduce with the `clj-java-decompiler` lib). With this, the lib is downloaded successfully from Clojars with no error messages from `lein-git-down` (and I also tried reordering my repositories so the GitHub repo ran first and still no error message):

```clojure
(defproject test-project "0.1.0-SNAPSHOT"
  :plugins [[reifyhealth/lein-git-down "0.3.4"]]
  :repositories  [["private-github" {:url "git://github.com" :protocol :ssh}]]
  :middleware [lein-git-down.plugin/inject-properties]
  :git-down {com.clojure-goes-fast/clj-java-decompiler {:coordinates clojure-goes-fast/clj-java-decompiler}}
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [com.clojure-goes-fast/clj-java-decompiler "0.2.1-SNAPSHOT"]])
```

Do you have any other details which might help isolate the problem?

**Comment by vemv** [comment]
Hey there,

sorry for the delay.

I haven't spun up l-g-d in a while and I couldn't get a deterministic repro anyway (particularly the affected project being large/private), so this issue seems best closed.
