### ISSUE TITLE
Not resolving source-directory

### ISSUE THREAD

**Issue by brokebroke** [reifyhealth/lein-git-down#32]
Just discovered this plugin, seems to perfect thing to play around with `org.clojure/spec-alpha2` while it's still under development. I'm running into an issue though, where the generated `project.clj` points to `src` for the `:source-path` but the `pom.xml` manifest is aiming at 

```
:configuration
     {:sourceDirectories {:sourceDirectory "src/main/clojure"},
      :testSourceDirectories {:testSourceDirectory "src/test/clojure"}}
```

The plugin as I can tell just looks for path `[:build :sourceDirectory]` and ignores the `:src-root` parameter for maven projects.

This is how I've configured the `project.clj`. Can load a REPL find, but fails to `(require '[clojure.spec-alpha2])`
```
 (defproject spec2 "0.1.0-SNAPSHOT"
  :description "spec-alpha2 test project"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :plugins [[reifyhealth/lein-git-down "0.3.3"]]
  :middleware [lein-git-down.plugin/inject-properties]
  :git-down {org.clojure/spec-alpha2 {:coordinates clojure/spec-alpha2
                                      :src-root "src/main/clojure/"}}
  :repositories [["public-github" {:url "git://github.com" :protocol :https}]]
  :dependencies [[org.clojure/clojure "1.10.0"]
                 [org.clojure/spec-alpha2 "29a73a3e5fef8329c14dd44a0b151e90b86c0854"]
                 [reifyhealth/lein-git-down "0.3.3"]]
  :main ^:skip-aot spec2.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

**Comment by manderson202** [comment]
Thanks for opening the issue and providing good detail. The `:src-root` parameter is only for repositories that have unknown (or missing) manifests at this point, which is why that's not working for you. Looks like we need to allow that to override known manifests and/or recognize the alternate pom source directory location. I'll take a look and get back to you.

**Comment by manderson202** [comment]
FYI: the fix for this should now be in the latest version `0.3.5` available in Clojars.

**Comment by brokebroke** [comment]
Fantastic, thanks for the fast turnaround.
