### ISSUE TITLE
Difference between windows vs macos + linux

### ISSUE THREAD

**Issue by Folcon** [reifyhealth/lein-git-down#52]
I'm not sure why, but I'm getting a difference is deps resolution between mac / linux vs windows:

I've been using github actions and debugging this, so I've got a current build log which I'll pull in the relevant segments.

[linux](https://github.com/Folcon/fruit-economy/runs/4946666885?check_suite_focus=true#step:12:186):
```bash
Retrieving humbleui/humbleui/fc60fd319ba905dada9a6917a1a1632413c132d5/humbleui-fc60fd319ba905dada9a6917a1a1632413c132d5.jar from public-github
Created /home/runner/.gitlibs/libs/humbleui/humbleui/fc60fd319ba905dada9a6917a1a1632413c132d5/target/humbleui-0.1.0.jar
Compiling 2 source files to /home/runner/work/fruit-economy/fruit-economy/target/classes
Compiling fruit-economy.core
```

[macos](https://github.com/Folcon/fruit-economy/runs/4946666907?check_suite_focus=true#step:12:186):
```bash
Retrieving humbleui/humbleui/fc60fd319ba905dada9a6917a1a1632413c132d5/humbleui-fc60fd319ba905dada9a6917a1a1632413c132d5.jar from public-github
Created /Users/runner/.gitlibs/libs/humbleui/humbleui/fc60fd319ba905dada9a6917a1a1632413c132d5/target/humbleui-0.1.0.jar
Compiling 2 source files to /Users/runner/work/fruit-economy/fruit-economy/target/classes
Compiling fruit-economy.core
```

[windows](https://github.com/Folcon/fruit-economy/runs/4946666937?check_suite_focus=true#step:10:194):
```bash
Retrieving humbleui/humbleui/fc60fd319ba905dada9a6917a1a1632413c132d5/humbleui-fc60fd319ba905dada9a6917a1a1632413c132d5.jar from public-github
Created C:\Users\runneradmin\.gitlibs\libs\humbleui\humbleui\fc60fd319ba905dada9a6917a1a1632413c132d5\target\humbleui-0.1.0.jar
Could not find artifact humbleui:humbleui:jar:fc60fd319ba905dada9a6917a1a1632413c132d5 in central (https://repo1.maven.org/maven2/)
Could not find artifact humbleui:humbleui:jar:fc60fd319ba905dada9a6917a1a1632413c132d5 in clojars (https://repo.clojars.org/)
Could not transfer artifact humbleui:humbleui:jar:fc60fd319ba905dada9a6917a1a1632413c132d5 from/to public-github (git://github.com): Checksum validation failed, no checksums available
Failed to read artifact descriptor for humbleui:humbleui:jar:fc60fd319ba905dada9a6917a1a1632413c132d5
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Uberjar aborting because jar failed: Could not resolve dependencies
```

No idea why this is happening, hopefully there's an obvious step I've been missing?

I'm assuming the problem is at this level and not [`leiningen`](https://github.com/technomancy/leiningen)?

Some additional context,  [the project.clj is here](https://github.com/Folcon/fruit-economy/blob/master/project.clj#L30).

**Comment by manderson202** [comment]
Thanks for the detailed report! It looks like something with the checksum step in the plugin is behaving differently on Windows. I'll leave this open until it can be more properly investigated.

**Comment by Folcon** [comment]
Do you need me to do anything? I have ready access to a windows machine =)...

**Comment by manderson202** [comment]
Thanks for the offer! PR's are welcome, so if you have the time/inclination, feel free to dive in 😄 

Otherwise, I may reach out for validation when there is time to circle back on this, but unfortunately time has been in short supply lately so I can't guarantee when this will get some attention.

It it is indeed an issue with the checksum, [this is the code](https://github.com/reifyhealth/lein-git-down/blob/develop/src/lein_git_down/git_wagon.clj#L280-L311) that handles it.

**Comment by Folcon** [comment]
It turns out to be a file separator problem...

On Mac:
```clojure
(str/split "~/.m2/repository/humbleui/humbleui/fc60fd319ba905dada9a6917a1a1632413c132d5/humbleui-fc60fd319ba905dada9a6917a1a1632413c132d5.jar" (re-pattern (str "\\" File/separatorChar)))
#_#_=> ["~" ".m2" "repository" "humbleui" "humbleui" "fc60fd319ba905dada9a6917a1a1632413c132d5" "humbleui-fc60fd319ba905dada9a6917a1a1632413c132d5.jar"]
```

On Win:
```clojure
TODO FROM WIN
```

**Comment by Folcon** [comment]
Thanks @manderson202, for merging that issue, I'm still uncertain about this bit?

> The story isn't quite over, I'm now getting:
> 
> ```shell
> Retrieving io/github/humbleui/jwm/b3fecb126a/jwm-b3fecb126a.pom from public-github
> Retrieving io/github/humbleui/jwm/b3fecb126a/jwm-b3fecb126a.jar from public-github
> Could not find artifact io.github.humbleui:jwm:jar:b3fecb126a in central (https://repo1.maven.org/maven2/)
> Could not find artifact io.github.humbleui:jwm:jar:b3fecb126a in clojars (https://repo.clojars.org/)
> Could not transfer artifact io.github.humbleui:jwm:jar:b3fecb126a from/to public-github (git://github.com): https://github.com/io.github.humbleui/jwm: Authentication
>  is required but no CredentialsProvider has been registered
> Could not transfer artifact io.github.humbleui:jwm:pom:b3fecb126a from/to public-github (git://github.com): https://github.com/io.github.humbleui/jwm: Authentication
>  is required but no CredentialsProvider has been registered
> ```
> 
> Once again not something I see at all on macos + linux.
> 
> Where's this code? I can take a quick look...

**Comment by manderson202** [comment]
Thanks for the PR! As for the above... Looks like the project it's trying to pull down, HumbleUI/JWM, doesn't have a recognized build file (eg: pom.xml, project.clj, or deps.edn), so it's probably falling into the [default jar resolve multimethod impl](https://github.com/reifyhealth/lein-git-down/blob/develop/src/lein_git_down/git_wagon.clj#L259-L271). I'm not sure why you're not getting errors on that one on other OS's, but not sure lein-git-down can build this library.

**Comment by Folcon** [comment]
@manderson202, you're right. For some reason the powershell version of maven can't seem to build it and so I had to resort to `wsl`, however I forgot that `wsl` has it's own `.m2` repository which it stores in `~/.m2/repository/` and not window's one at `/mnt/c/Users/<Username>/.m2/repository/`.

So I had to do: `<maven unzip location>/bin/mvn install:install-file -Dfile=jwm-b3fecb126a.jar -DpomFile=maven/META-INF/maven/io.github.humbleui/jwm/pom.xml -DlocalRepositoryPath=/mnt/c/Users/<Username>/.m2/repository/`.

Sigh...

Anyway, could you please cut a release on clojars or somewhere so I can use the latest version in my github actions?

**Comment by manderson202** [comment]
Just pushed the release. Thanks again for the detailed issue report and the fix!

**Comment by Folcon** [comment]
Just an quick update @manderson202 to say thank you =)...

[Managed to get this working](https://github.com/Folcon/fruit-economy/actions/runs/1766008578) thanks to your help!
